Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC1.Context;
using MVC1.Models;
namespace MVC1.Controllers
{
    public class CourseController : Controller
    {
        Unitxt db = new Unitxt();

        public IActionResult Delete(int id)
        {
            // Find the course and include related instructors and course results (crsResult)
            var course = db.Courses
                           .Include(c => c.Instructors)   // Include related instructors
                           .Include(c => c.crsResults)    // Include related course results
                           .FirstOrDefault(c => c.Id == id);  // Find course by id

            if (course == null)
            {
                return NotFound();
            }

            
           

            // handle related course results
            if (course.crsResults != null)
            {
                foreach (var crsResult in course.crsResults)
                {
                    crsResult.CrsId = null;  // Set foreign key to null 
                }
            }

            
            db.Courses.Remove(course);
            db.SaveChanges();

            return RedirectToAction("GetAll");  // Redirect to the Index page
        }



        public IActionResult Update(int id)
        {
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var crsres = db.crsResults.ToList();
            ViewBag.crsResults = crsres;
            var cr = db.Courses.Find(id);
            return View(cr);
        }

        [HttpPost]
        public IActionResult SaveUpdate(Course c)
        {
            if (c.Name!=null)

            {
                db.Courses.Update(c);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var crsres = db.crsResults.ToList();
            ViewBag.crsResults = crsres;
            return View("Update", c);
        }

        [HttpPost]
        public IActionResult SaveNew(Course c)
        {
            if (ModelState.IsValid)

            {
                db.Courses.Add(c);
                db.SaveChanges();
                return RedirectToAction("GetAll");

            }

            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var crsres = db.crsResults.ToList();
            ViewBag.crsResults = crsres;

            return View("New", c);
        }


        public IActionResult New()
        {
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var crsres = db.crsResults.ToList();
            ViewBag.crsResults = crsres;
            return View();
        }

        public IActionResult GetAll()
        {
            var crses = db.Courses.ToList();
            return View(crses);
            
        }
        public IActionResult Details(int id)
        {
            var crss = db.Courses.Include(c => c.Department).FirstOrDefault(c => c.Id == id);
            return View(crss);
        }
    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC1.Context;
using MVC1.Models;

namespace MVC1.Controllers
{
	public class DepartmentController : Controller
	{
        Unitxt db = new Unitxt();


        public IActionResult Delete(int id)
        {
            
            var depart = db.Departments
                           .Include(c => c.Instructors)   
                           .Include(c => c.Courses)    
                           .FirstOrDefault(c => c.DeptId == id);  

            if (depart == null)
            {
                return NotFound();
            }



            if (depart.Instructors != null)
            {
                foreach (var instructor in depart.Instructors)
                {
                    instructor.DeptId = null;  // Set foreign key to null
                }
            }

            db.Departments.Remove(depart);
            db.SaveChanges();

            return RedirectToAction("GetAll");  // Redirect to the appropriate action
        }


        public IActionResult Update(int id)
		{
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			
			var dp = db.Departments.Find(id);
			return View(dp);
		}

		[HttpPost]
		public IActionResult SaveUpdate(Department d)
		{
			if (ModelState.IsValid)

			{
				db.Departments.Update(d);
				db.SaveChanges();
				return RedirectToAction("GetAll");
			}
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			
			return View("Update", d);
		}

		[HttpPost]
        public IActionResult SaveNew(Department d)
        {
            if (ModelState.IsValid)

            {
                db.Departments.Add(d);
                db.SaveChanges();
                return RedirectToAction("GetAll");

            }

            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            

            return View("New", d);
        }

        public IActionResult New()
        {
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            
            return View();
        }
        public IActionResult GetAll()
		{
            var depts = db.Departments.ToList();
            return View(depts);
        }
        public IActionResult Details(int id)
        {
            var depts = db.Departments.Include(d => d.Courses).FirstOrDefault(d => d.DeptId == id);
            return View(depts);
        }
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC1.Context;
using MVC1.Models;

namespace MVC1.Controllers
{
	public class InstructorController : Controller
	{
		Unitxt db = new Unitxt();
        
        public IActionResult Delete(int id)
        {
            var ins = db.Instructors.Find(id);
            db.Instructors.Remove(ins);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var crses = db.Courses.ToList();
            ViewBag.Courses = crses;
            var ins = db.Instructors.Find(id);
            return View(ins);
        }

        [HttpPost]
        public IActionResult SaveUpdate(Instructor i)
        {
            if(ModelState.IsValid)
            
            {
                db.Instructors.Update(i);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
			var crses = db.Courses.ToList();
			ViewBag.Courses = crses;
			return View("Update", i);
        }

       
        

        [HttpPost]
        public IActionResult SaveNew(Instructor i)
        {
            if (ModelState.IsValid)
        
            {
                db.Instructors.Add(i);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
			var crses = db.Courses.ToList();
			ViewBag.Courses = crses;

			return View("New",i);
        }

       
        public IActionResult New()
		{
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
			var crses = db.Courses.ToList();
			ViewBag.Courses = crses;
			return View();
		}
		public IActionResult Index()
		{
			var ins = db.Instructors.ToList(); 
			return View(ins);
		}

        public IActionResult Details(int id)
		{

            //var inss = db.Instructors.Find(id);
            var inss = db.Instructors.Include(i => i.Department).FirstOrDefault(i => i.Id == id);
            return View(inss);
		}
	}
}

Controllers/TraineeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC1.Context;
using MVC1.Models;
using MVC1.ViewModels;

namespace MVC1.Controllers
{
    public class TraineeController : Controller
    {
        Unitxt db = new Unitxt();

        public IActionResult Delete(int id)
        {
            // Find the trainee and include related course results (crsResult)
            var trainee = db.Trainees
                            .Include(t => t.crsResults)  // Include related course results
                            .FirstOrDefault(t => t.Id == id);  // Find trainee by id

            if (trainee == null)
            {
                return NotFound();
            }

            // Disassociate related course results (set TraineeId to null)
            if (trainee.crsResults != null)
            {
                foreach (var crsResult in trainee.crsResults)
                {
                    crsResult.TraineeId = null;  // Set foreign key to null
                }
            }

            // Remove the trainee
            db.Trainees.Remove(trainee);
            db.SaveChanges();

            return RedirectToAction("GetAll");
        }

        //public IActionResult Delete(int id)
        //{
        //	var tr = db.Trainees.Find(id);
        //	db.Trainees.Remove(tr);
        //	db.SaveChanges();
        //	return RedirectToAction("GetAll");
        //}

        public IActionResult Update(int id)
		{
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			var crsres = db.crsResults.ToList();
			ViewBag.crsResults = crsres;
			var tr = db.Trainees.Find(id);
			return View(tr);
		}

		[HttpPost]
		public IActionResult SaveUpdate(Trainee t)
		{
			if (t.Name != null)

			{
				db.Trainees.Update(t);
				db.SaveChanges();
				return RedirectToAction("GetAll");
			}
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			var crsres = db.crsResults.ToList();
			ViewBag.crsResults = crsres;
			return View("Update", t);
		}

		[HttpPost]
		public IActionResult SaveNew(Trainee t)
		{
			if (t.Name != null)

			{
				db.Trainees.Add(t);
				db.SaveChanges();
				return RedirectToAction("GetAll");

			}

			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			var crsres = db.crsResults.ToList();
			ViewBag.crsResults = crsres;

			return View("New", t);
		}


		public IActionResult New()
		{
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
			var crsres = db.crsResults.ToList();
			ViewBag.crsResults = crsres;
			return View();
		}
		public IActionResult GetAll()
        {
            var trs = db.Trainees.Include(t => t.Department).ToList();  
            return View(trs);
        }

        // Action to get the detailed view of a trainee by id
        public IActionResult DetailsVM(int id)
        {
            var trainee = db.Trainees
                            .Include(t => t.Department)              
                            .Include(t => t.crsResults)              
                                .ThenInclude(cr => cr.Course)        
                            .FirstOrDefault(t => t.Id == id);         


            // Create a ViewModel to pass the detailed information to the view
            var traineeViewModel = new TraineeViewModel
            {
                TraineeId = trainee.Id,
                TraineeName = trainee.Name,
                Address = trainee.Address,
                Image = trainee.Image,
                DepartmentName = trainee.Department.DeptName,  
                Courses = trainee.crsResults.Select(cr => new CourseResultViewModel
                {
                    CourseName = cr.Course.Name,    
                    Grade = cr.Degree,
                    MinimumGrade = cr.Course.MinDegree     
                }).ToList()
            };

           
            return View(traineeViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Education System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Education System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Education System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Education System</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Education system</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" asp-action="Index" asp-controller="Instructor">Instructors</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="GetAll" asp-controller="Trainee">Trainees</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="GetAll" asp-controller="Course">Courses</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="GetAll" asp-controller="Department">Departments</a></li>
                         @*<li class="nav-item dropdown">
                             <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                             <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                 <li><a class="dropdown-item" href="#">Action</a></li>
                                 <li><a class="dropdown-item" href="#">Another action</a></li>
                                 <li><hr class="dropdown-divider" /></li>
                                 <li><a class="dropdown-item" href="#">Something else here</a></li>
                             </ul>
                         </li>*@
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>Education System Portal</h1>
                <p class="lead">people develop countries we develop people</p>
                <p>By: Mariam Abdelgalil</p>
            </div>
        @RenderBody()
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/js/scripts.js"></script>
    </body>
</html>
@RenderSection("scripts",false)